---
title: "Convert CONAGUA Diarios Temperatures to Raster File"
output: html_notebook
---

```{r}
library(dplyr)
library(stringr)
library(stringi)
library(tidyverse)
library(lubridate)
```


## Create a list of files that are Mensuales 
Yes, when we downloaded the files, we did not check whether the files names were consistent.
Then we filter on file urls that contains the 'Mensuales' keyword to scrap the monthly average value per station.

```{r}
cols_url <- paste("V", 1:7,sep='_')
df.files <- read.csv('data/conagua_files_list.csv',encoding = 'utf-8')
df.files.gather<- df.files %>% dplyr::select(c('ID',cols_url )) %>% gather(key=vector,value=url,-ID)
df.files.diarios <- df.files.gather %>% dplyr::filter(.,grepl('Diarios',url))
str(df.files.diarios)
head(df.files.diarios)
df.files.diarios$filename<- paste(df.files.diarios$ID,df.files.diarios$vector,'.txt',sep='')
```



## Read the full history file and retrieve the station informations 

```{r}
get_stations_diarios <- function(file_){
  
  tryCatch({
  
  DATA_FOLDER <- 'data/sonaguas'
 
  filename <-paste(DATA_FOLDER,file_,sep='/')
  
  con <- file(filename)
  lns <- readLines(filename)
  
  col.names <- c('date','PRECIP','EVAP' ,'TMAX','TMIN')
  
  start.read.diarios <- grep('FECHA',lns)[1]+1
  end.read.diarios <- grep('---------',lns)[-1]
  
  
   if((length(start.read.diarios)>0) & (length(end.read.diarios)>0)){
 
  df.diarios <- read.fwf(filename, width=c(11,rep(7,each=4)),
                         col.names=col.names,
                         skip=start.read.diarios,
                         n=end.read.diarios-start.read.diarios-1,
                         encoding = 'UTF-8')
  
 
  close(con)
  
  }
  },error=function(cond) {
            message(paste("file could not be wrapped :", filename))
  })
  
  df.diarios$date <- dmy(df.diarios$date)
  df.diarios <- df.diarios  %>% dplyr::filter(date>as.Date('2004-12-31'))
df.diarios$TMAX <- as.numeric(as.character(df.diarios$TMAX))
df.diarios$TMIN <- as.numeric(as.character(df.diarios$TMIN))
df.diarios$ESTACION <- file_
  
  return(df.diarios %>% select(ESTACION,date,TMAX,TMIN))
}

```


```{r}
df.test <- get_stations_diarios('1001V_1.txt')

```

```{r}

retrieve_all_diarios <- function(){
  df<-as.data.frame(c('a'))
  for(f in df.files.diarios$filename){
    tryCatch({
      df <- bind_rows(df,get_stations_diarios(f))
      print(which(df.files.diarios$filename==f)/length(df.files.diarios$filename)*100)
    },error=function(cond) {
            message(paste("file could not be wrapped :", f))
  }
    )
  }
  return (df)
}

df <- retrieve_all_diarios()
write.csv(df, 'data/conagua_diarios.csv')
```

