---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(rgdal)
library(rgeos)
library(readstata13)
library(ncdf4)
library(raster)
library(stringr)
library(gridExtra)
library(RColorBrewer)
library(classInt)
library(plotrix)    # Créer des échelles de couleurs

```
GIS Data
```{r}
muni.gis <- readOGR(dsn="gis/shapefiles/conjunto_de_datos/",layer = "areas_geoestadisticas_municipales")
muni.gis@data <- muni.gis@data %>% mutate(id = paste(CVE_ENT,CVE_MUN,sep=''))
muni.gis@data
```
### Retrieve the centroids of each MUNID
```{r}
trueCentroids = gCentroid(muni.gis,byid=TRUE)
plot(muni.gis)
points(coordinates(muni.gis),pch=1)
points(trueCentroids,pch=2)
```



```{r}
df.tariffa<-  read.dta13('gis/tariff/Tariffs.dta')
summary(df.tariffa)
```
### Combine Tariffa with GIS data
```{r}
muni.gis@data<- left_join(muni.gis@data,df.tariffa, by='id')
head(muni.gis@data)

muni.gis@data$tarifa.num<- as.numeric(muni.gis@data$tarifa)

unique(muni.gis@data$tarifa.num)
```
### Plot tariffa map

```{r}
plot_map_region<- function(comm,feature,color_hex,title,ratio){
  color_hex_min='#404040'
  color_hex_max=color_hex
  
  data.comm<- comm@data %>% mutate(feature = ifelse(is.na(feature),mean(feature),feature))
  data.comm<- data.comm %>% filter(month==10 & year==2010)
  data <- data.comm[,feature]
  print(class(data))

  col <- findColours(classIntervals(
            data, 10, style="quantile"),
            smoothColors(color_hex_min,3,'white',2,color_hex_max))

leg <- findColours(classIntervals(
            round(data*ratio,0), 5, style="quantile"),
            smoothColors(color_hex_min,3,'white',2,color_hex_max),
            under="<", over=">", between="–",
            cutlabels=FALSE)

plot(comm,   col=col, border='green', lwd=.1,main=title)



plot(comm,   col=col, border=col, lwd=.1,main=title,add=TRUE)


legend("bottomleft",fill=attr(leg, "palette"),
    legend=gsub("\\.", ",", names(attr(leg,"table"))),
    title = paste(title," :"),bty = "n",cex=1)
  
}

muni.gis.01<- subset(muni.gis,id=='01001')
muni.gis.abasolo<- subset(muni.gis.01,NOM_MUN=='Abasolo')

plot_map_region(muni.gis,'tarifa.num',"#ca0020",'Tarifa Family',ratio=1)
```
### Extract Air temperature for Mexico

```{r}
filename = 'gis/noaa_temperatures/air.mon.mean.nc'
nc<-   nc_open(filename)
names(nc$var)
summary(nc)
```
Crop on mex
```{r}
rasta<-raster(filename)

e <- extent(240,289,0,40)
rc <- crop(rasta, e)
plot(rc[[1]])
```



```{r}
df.air_temp_xy <- as.data.frame(cropped.r, xy = TRUE)
df.air_temp_xy<- df.air_temp_xy %>% filter(x>240 & x<289 & y>0 & y<40)
plot(df.air_temp_xy$x,df.air_temp_xy$y,col=df.air_temp_xy$X1964.08.01.00.06.32)
```



